// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getArtifact = `-- name: GetArtifact :one
SELECT a.id, a.cluster_id, c.name AS cluster_name, a.kind, a.namespace,
       a.owner_kind, a.owner_name, a.identity, a.installed_version,
       a.source_meta, a.first_seen, a.last_seen,
       o.latest_version,
       COALESCE(o.drift_class, 'unknown')::text AS drift_class,
       COALESCE(o.drift_score, 0)::double precision AS drift_score,
       o.releases_behind, o.confidence
FROM artifacts a
JOIN clusters c ON c.id = a.cluster_id
LEFT JOIN LATERAL (
    SELECT ob.latest_version, ob.drift_class, ob.drift_score, ob.releases_behind, ob.confidence
    FROM observations ob
    JOIN scans s ON s.id = ob.scan_id
    WHERE ob.artifact_id = a.id
    ORDER BY s.started_at DESC
    LIMIT 1
) o ON true
WHERE a.id = $1
`

type GetArtifactRow struct {
	ID               uuid.UUID          `json:"id"`
	ClusterID        uuid.UUID          `json:"cluster_id"`
	ClusterName      string             `json:"cluster_name"`
	Kind             string             `json:"kind"`
	Namespace        string             `json:"namespace"`
	OwnerKind        string             `json:"owner_kind"`
	OwnerName        string             `json:"owner_name"`
	Identity         string             `json:"identity"`
	InstalledVersion string             `json:"installed_version"`
	SourceMeta       []byte             `json:"source_meta"`
	FirstSeen        pgtype.Timestamptz `json:"first_seen"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
	LatestVersion    pgtype.Text        `json:"latest_version"`
	DriftClass       string             `json:"drift_class"`
	DriftScore       float64            `json:"drift_score"`
	ReleasesBehind   pgtype.Int4        `json:"releases_behind"`
	Confidence       pgtype.Float4      `json:"confidence"`
}

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (GetArtifactRow, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i GetArtifactRow
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.ClusterName,
		&i.Kind,
		&i.Namespace,
		&i.OwnerKind,
		&i.OwnerName,
		&i.Identity,
		&i.InstalledVersion,
		&i.SourceMeta,
		&i.FirstSeen,
		&i.LastSeen,
		&i.LatestVersion,
		&i.DriftClass,
		&i.DriftScore,
		&i.ReleasesBehind,
		&i.Confidence,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT a.id, a.cluster_id, c.name AS cluster_name, a.kind, a.namespace,
       a.owner_kind, a.owner_name, a.identity, a.installed_version, a.last_seen,
       o.latest_version,
       COALESCE(o.drift_class, 'unknown')::text AS drift_class,
       COALESCE(o.drift_score, 0)::double precision AS drift_score,
       o.releases_behind
FROM artifacts a
JOIN clusters c ON c.id = a.cluster_id
LEFT JOIN LATERAL (
    SELECT ob.latest_version, ob.drift_class, ob.drift_score, ob.releases_behind
    FROM observations ob
    JOIN scans s ON s.id = ob.scan_id
    WHERE ob.artifact_id = a.id
    ORDER BY s.started_at DESC
    LIMIT 1
) o ON true
WHERE ($1::uuid IS NULL OR a.cluster_id = $1)
  AND ($2::text IS NULL OR a.kind = $2)
  AND ($3::text IS NULL OR a.namespace = $3)
  AND ($4::text IS NULL OR o.drift_class = $4)
  AND ($5::text IS NULL OR a.identity ILIKE '%' || $5 || '%')
ORDER BY COALESCE(o.drift_score, -1) DESC, a.identity ASC, a.id ASC
OFFSET $6
LIMIT $7
`

type ListArtifactsParams struct {
	Cluster   pgtype.UUID `json:"cluster"`
	Kind      pgtype.Text `json:"kind"`
	Namespace pgtype.Text `json:"namespace"`
	Class     pgtype.Text `json:"class"`
	Q         pgtype.Text `json:"q"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

type ListArtifactsRow struct {
	ID               uuid.UUID          `json:"id"`
	ClusterID        uuid.UUID          `json:"cluster_id"`
	ClusterName      string             `json:"cluster_name"`
	Kind             string             `json:"kind"`
	Namespace        string             `json:"namespace"`
	OwnerKind        string             `json:"owner_kind"`
	OwnerName        string             `json:"owner_name"`
	Identity         string             `json:"identity"`
	InstalledVersion string             `json:"installed_version"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
	LatestVersion    pgtype.Text        `json:"latest_version"`
	DriftClass       string             `json:"drift_class"`
	DriftScore       float64            `json:"drift_score"`
	ReleasesBehind   pgtype.Int4        `json:"releases_behind"`
}

// ListArtifacts returns each artifact with its most recent observation (the drift
// from the latest scan that saw it). Filters are optional (NULL = no filter).
// Default sort is drift_score desc (SPEC §5.5). One extra row is fetched by the
// caller (lim = pageSize+1) to detect whether another page exists.
func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArtifacts,
		arg.Cluster,
		arg.Kind,
		arg.Namespace,
		arg.Class,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtifactsRow
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.ClusterName,
			&i.Kind,
			&i.Namespace,
			&i.OwnerKind,
			&i.OwnerName,
			&i.Identity,
			&i.InstalledVersion,
			&i.LastSeen,
			&i.LatestVersion,
			&i.DriftClass,
			&i.DriftScore,
			&i.ReleasesBehind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifacts (cluster_id, kind, namespace, owner_kind, owner_name, identity, installed_version, source_meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (cluster_id, kind, namespace, owner_kind, owner_name, identity)
DO UPDATE SET installed_version = EXCLUDED.installed_version,
              source_meta = EXCLUDED.source_meta,
              last_seen = now()
RETURNING id
`

type UpsertArtifactParams struct {
	ClusterID        uuid.UUID `json:"cluster_id"`
	Kind             string    `json:"kind"`
	Namespace        string    `json:"namespace"`
	OwnerKind        string    `json:"owner_kind"`
	OwnerName        string    `json:"owner_name"`
	Identity         string    `json:"identity"`
	InstalledVersion string    `json:"installed_version"`
	SourceMeta       []byte    `json:"source_meta"`
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.ClusterID,
		arg.Kind,
		arg.Namespace,
		arg.OwnerKind,
		arg.OwnerName,
		arg.Identity,
		arg.InstalledVersion,
		arg.SourceMeta,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
