// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCluster = `-- name: CreateCluster :one

INSERT INTO clusters (name, api_server_url, context, kubeconfig_enc, kubeconfig_nonce, rbac_report, schedule_cron, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, api_server_url, rbac_report, schedule_cron, created_at, last_scan_at, status
`

type CreateClusterParams struct {
	Name            string `json:"name"`
	ApiServerUrl    string `json:"api_server_url"`
	Context         string `json:"context"`
	KubeconfigEnc   []byte `json:"kubeconfig_enc"`
	KubeconfigNonce []byte `json:"kubeconfig_nonce"`
	RbacReport      []byte `json:"rbac_report"`
	ScheduleCron    string `json:"schedule_cron"`
	Status          string `json:"status"`
}

type CreateClusterRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	ApiServerUrl string             `json:"api_server_url"`
	RbacReport   []byte             `json:"rbac_report"`
	ScheduleCron string             `json:"schedule_cron"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastScanAt   pgtype.Timestamptz `json:"last_scan_at"`
	Status       string             `json:"status"`
}

// Kubeconfig columns are intentionally excluded from list/get queries; the
// encrypted blob is only readable via GetClusterKubeconfig (scanner use).
func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (CreateClusterRow, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.Name,
		arg.ApiServerUrl,
		arg.Context,
		arg.KubeconfigEnc,
		arg.KubeconfigNonce,
		arg.RbacReport,
		arg.ScheduleCron,
		arg.Status,
	)
	var i CreateClusterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiServerUrl,
		&i.RbacReport,
		&i.ScheduleCron,
		&i.CreatedAt,
		&i.LastScanAt,
		&i.Status,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :execrows
DELETE FROM clusters WHERE id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCluster, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCluster = `-- name: GetCluster :one
SELECT id, name, api_server_url, rbac_report, schedule_cron, created_at, last_scan_at, status
FROM clusters
WHERE id = $1
`

type GetClusterRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	ApiServerUrl string             `json:"api_server_url"`
	RbacReport   []byte             `json:"rbac_report"`
	ScheduleCron string             `json:"schedule_cron"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastScanAt   pgtype.Timestamptz `json:"last_scan_at"`
	Status       string             `json:"status"`
}

func (q *Queries) GetCluster(ctx context.Context, id uuid.UUID) (GetClusterRow, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i GetClusterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiServerUrl,
		&i.RbacReport,
		&i.ScheduleCron,
		&i.CreatedAt,
		&i.LastScanAt,
		&i.Status,
	)
	return i, err
}

const getClusterConnection = `-- name: GetClusterConnection :one
SELECT id, name, context, kubeconfig_enc, kubeconfig_nonce, rbac_report, schedule_cron
FROM clusters
WHERE id = $1
`

type GetClusterConnectionRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Context         string    `json:"context"`
	KubeconfigEnc   []byte    `json:"kubeconfig_enc"`
	KubeconfigNonce []byte    `json:"kubeconfig_nonce"`
	RbacReport      []byte    `json:"rbac_report"`
	ScheduleCron    string    `json:"schedule_cron"`
}

// GetClusterConnection returns everything the scanner needs to reach a cluster.
// The encrypted kubeconfig never leaves the backend (SPEC §2.6).
func (q *Queries) GetClusterConnection(ctx context.Context, id uuid.UUID) (GetClusterConnectionRow, error) {
	row := q.db.QueryRow(ctx, getClusterConnection, id)
	var i GetClusterConnectionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Context,
		&i.KubeconfigEnc,
		&i.KubeconfigNonce,
		&i.RbacReport,
		&i.ScheduleCron,
	)
	return i, err
}

const getClusterKubeconfig = `-- name: GetClusterKubeconfig :one
SELECT kubeconfig_enc, kubeconfig_nonce
FROM clusters
WHERE id = $1
`

type GetClusterKubeconfigRow struct {
	KubeconfigEnc   []byte `json:"kubeconfig_enc"`
	KubeconfigNonce []byte `json:"kubeconfig_nonce"`
}

func (q *Queries) GetClusterKubeconfig(ctx context.Context, id uuid.UUID) (GetClusterKubeconfigRow, error) {
	row := q.db.QueryRow(ctx, getClusterKubeconfig, id)
	var i GetClusterKubeconfigRow
	err := row.Scan(&i.KubeconfigEnc, &i.KubeconfigNonce)
	return i, err
}

const listClusterSchedules = `-- name: ListClusterSchedules :many
SELECT id, name, schedule_cron, last_scan_at
FROM clusters
ORDER BY name
`

type ListClusterSchedulesRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	ScheduleCron string             `json:"schedule_cron"`
	LastScanAt   pgtype.Timestamptz `json:"last_scan_at"`
}

func (q *Queries) ListClusterSchedules(ctx context.Context) ([]ListClusterSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listClusterSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClusterSchedulesRow
	for rows.Next() {
		var i ListClusterSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ScheduleCron,
			&i.LastScanAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusters = `-- name: ListClusters :many
SELECT id, name, api_server_url, rbac_report, schedule_cron, created_at, last_scan_at, status
FROM clusters
ORDER BY name
`

type ListClustersRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	ApiServerUrl string             `json:"api_server_url"`
	RbacReport   []byte             `json:"rbac_report"`
	ScheduleCron string             `json:"schedule_cron"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastScanAt   pgtype.Timestamptz `json:"last_scan_at"`
	Status       string             `json:"status"`
}

func (q *Queries) ListClusters(ctx context.Context) ([]ListClustersRow, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClustersRow
	for rows.Next() {
		var i ListClustersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiServerUrl,
			&i.RbacReport,
			&i.ScheduleCron,
			&i.CreatedAt,
			&i.LastScanAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterSchedule = `-- name: UpdateClusterSchedule :exec
UPDATE clusters SET schedule_cron = $2 WHERE id = $1
`

type UpdateClusterScheduleParams struct {
	ID           uuid.UUID `json:"id"`
	ScheduleCron string    `json:"schedule_cron"`
}

func (q *Queries) UpdateClusterSchedule(ctx context.Context, arg UpdateClusterScheduleParams) error {
	_, err := q.db.Exec(ctx, updateClusterSchedule, arg.ID, arg.ScheduleCron)
	return err
}
