// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fleetLaneRollup = `-- name: FleetLaneRollup :many
SELECT c.id AS cluster_id, c.name AS cluster_name, c.status AS cluster_status,
       c.last_scan_at,
       COUNT(o.artifact_id)::int AS total,
       COUNT(o.artifact_id) FILTER (WHERE o.drift_class = 'current')::int AS current,
       COUNT(o.artifact_id) FILTER (WHERE o.drift_class = 'patch')::int AS patch,
       COUNT(o.artifact_id) FILTER (WHERE o.drift_class = 'minor')::int AS minor,
       COUNT(o.artifact_id) FILTER (WHERE o.drift_class = 'major')::int AS major,
       COUNT(o.artifact_id) FILTER (WHERE o.drift_class = 'deprecated')::int AS deprecated,
       COUNT(o.artifact_id) FILTER (WHERE o.drift_class = 'unknown')::int AS unknown
FROM clusters c
LEFT JOIN LATERAL (
    SELECT ls.id
    FROM scans ls
    WHERE ls.cluster_id = c.id AND ls.status = 'done'
    ORDER BY ls.finished_at DESC NULLS LAST, ls.started_at DESC
    LIMIT 1
) latest_scan ON true
LEFT JOIN observations o ON o.scan_id = latest_scan.id
GROUP BY c.id, c.name, c.status, c.last_scan_at
ORDER BY c.name
`

type FleetLaneRollupRow struct {
	ClusterID     uuid.UUID          `json:"cluster_id"`
	ClusterName   string             `json:"cluster_name"`
	ClusterStatus string             `json:"cluster_status"`
	LastScanAt    pgtype.Timestamptz `json:"last_scan_at"`
	Total         int32              `json:"total"`
	Current       int32              `json:"current"`
	Patch         int32              `json:"patch"`
	Minor         int32              `json:"minor"`
	Major         int32              `json:"major"`
	Deprecated    int32              `json:"deprecated"`
	Unknown       int32              `json:"unknown"`
}

// FleetLaneRollup returns, for every cluster, the drift-class breakdown of its
// latest completed scan (SPEC §2.7 GET /api/fleet/summary). Clusters with no
// completed scan yet still appear with all counts at zero (LEFT JOIN) so the
// fleet chart can render an empty lane instead of hiding the cluster.
func (q *Queries) FleetLaneRollup(ctx context.Context) ([]FleetLaneRollupRow, error) {
	rows, err := q.db.Query(ctx, fleetLaneRollup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetLaneRollupRow
	for rows.Next() {
		var i FleetLaneRollupRow
		if err := rows.Scan(
			&i.ClusterID,
			&i.ClusterName,
			&i.ClusterStatus,
			&i.LastScanAt,
			&i.Total,
			&i.Current,
			&i.Patch,
			&i.Minor,
			&i.Major,
			&i.Deprecated,
			&i.Unknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFleetScans = `-- name: ListRecentFleetScans :many
SELECT s.id, s.cluster_id, c.name AS cluster_name, s.started_at, s.finished_at, s.status, s.error
FROM scans s
JOIN clusters c ON c.id = s.cluster_id
ORDER BY s.started_at DESC
LIMIT $1
`

type ListRecentFleetScansRow struct {
	ID          uuid.UUID          `json:"id"`
	ClusterID   uuid.UUID          `json:"cluster_id"`
	ClusterName string             `json:"cluster_name"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Status      string             `json:"status"`
	Error       pgtype.Text        `json:"error"`
}

// ListRecentFleetScans returns the most recent scans across every cluster,
// newest first, for the fleet page's "last scans" rail. Includes failed scans
// so they can double as "failures needing attention".
func (q *Queries) ListRecentFleetScans(ctx context.Context, limit int32) ([]ListRecentFleetScansRow, error) {
	rows, err := q.db.Query(ctx, listRecentFleetScans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentFleetScansRow
	for rows.Next() {
		var i ListRecentFleetScansRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.ClusterName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
