// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: global_registry_auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteGlobalRegistryAuth = `-- name: DeleteGlobalRegistryAuth :exec
DELETE FROM global_registry_auth WHERE target = $1 AND kind = $2
`

type DeleteGlobalRegistryAuthParams struct {
	Target string `json:"target"`
	Kind   string `json:"kind"`
}

func (q *Queries) DeleteGlobalRegistryAuth(ctx context.Context, arg DeleteGlobalRegistryAuthParams) error {
	_, err := q.db.Exec(ctx, deleteGlobalRegistryAuth, arg.Target, arg.Kind)
	return err
}

const listGlobalRegistryAuth = `-- name: ListGlobalRegistryAuth :many
SELECT id, target, kind, method, username_enc, username_nonce, password_enc, password_nonce, created_at
FROM global_registry_auth
ORDER BY kind, target
`

func (q *Queries) ListGlobalRegistryAuth(ctx context.Context) ([]GlobalRegistryAuth, error) {
	rows, err := q.db.Query(ctx, listGlobalRegistryAuth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalRegistryAuth
	for rows.Next() {
		var i GlobalRegistryAuth
		if err := rows.Scan(
			&i.ID,
			&i.Target,
			&i.Kind,
			&i.Method,
			&i.UsernameEnc,
			&i.UsernameNonce,
			&i.PasswordEnc,
			&i.PasswordNonce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalRegistryAuth = `-- name: UpsertGlobalRegistryAuth :one
INSERT INTO global_registry_auth (target, kind, method, username_enc, username_nonce, password_enc, password_nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (target, kind) DO UPDATE SET
    method = EXCLUDED.method,
    username_enc = EXCLUDED.username_enc,
    username_nonce = EXCLUDED.username_nonce,
    password_enc = EXCLUDED.password_enc,
    password_nonce = EXCLUDED.password_nonce
RETURNING id
`

type UpsertGlobalRegistryAuthParams struct {
	Target        string `json:"target"`
	Kind          string `json:"kind"`
	Method        string `json:"method"`
	UsernameEnc   []byte `json:"username_enc"`
	UsernameNonce []byte `json:"username_nonce"`
	PasswordEnc   []byte `json:"password_enc"`
	PasswordNonce []byte `json:"password_nonce"`
}

func (q *Queries) UpsertGlobalRegistryAuth(ctx context.Context, arg UpsertGlobalRegistryAuthParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertGlobalRegistryAuth,
		arg.Target,
		arg.Kind,
		arg.Method,
		arg.UsernameEnc,
		arg.UsernameNonce,
		arg.PasswordEnc,
		arg.PasswordNonce,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
