// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: latest_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestCache = `-- name: GetLatestCache :one
SELECT identity, kind, latest_version, candidates, resolved_at, ttl,
       (resolved_at + ttl > now()) AS fresh
FROM latest_cache
WHERE identity = $1 AND kind = $2
`

type GetLatestCacheParams struct {
	Identity string `json:"identity"`
	Kind     string `json:"kind"`
}

type GetLatestCacheRow struct {
	Identity      string             `json:"identity"`
	Kind          string             `json:"kind"`
	LatestVersion pgtype.Text        `json:"latest_version"`
	Candidates    []byte             `json:"candidates"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	Ttl           pgtype.Interval    `json:"ttl"`
	Fresh         bool               `json:"fresh"`
}

func (q *Queries) GetLatestCache(ctx context.Context, arg GetLatestCacheParams) (GetLatestCacheRow, error) {
	row := q.db.QueryRow(ctx, getLatestCache, arg.Identity, arg.Kind)
	var i GetLatestCacheRow
	err := row.Scan(
		&i.Identity,
		&i.Kind,
		&i.LatestVersion,
		&i.Candidates,
		&i.ResolvedAt,
		&i.Ttl,
		&i.Fresh,
	)
	return i, err
}

const upsertLatestCache = `-- name: UpsertLatestCache :exec
INSERT INTO latest_cache (identity, kind, latest_version, candidates, resolved_at, ttl)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (identity, kind)
DO UPDATE SET latest_version = EXCLUDED.latest_version,
              candidates = EXCLUDED.candidates,
              resolved_at = now(),
              ttl = EXCLUDED.ttl
`

type UpsertLatestCacheParams struct {
	Identity      string          `json:"identity"`
	Kind          string          `json:"kind"`
	LatestVersion pgtype.Text     `json:"latest_version"`
	Candidates    []byte          `json:"candidates"`
	Ttl           pgtype.Interval `json:"ttl"`
}

func (q *Queries) UpsertLatestCache(ctx context.Context, arg UpsertLatestCacheParams) error {
	_, err := q.db.Exec(ctx, upsertLatestCache,
		arg.Identity,
		arg.Kind,
		arg.LatestVersion,
		arg.Candidates,
		arg.Ttl,
	)
	return err
}
