// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	ID             int32              `json:"id"`
	OciTtl         pgtype.Interval    `json:"oci_ttl"`
	HelmrepoTtl    pgtype.Interval    `json:"helmrepo_ttl"`
	ArtifacthubTtl pgtype.Interval    `json:"artifacthub_ttl"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Artifact struct {
	ID               uuid.UUID          `json:"id"`
	ClusterID        uuid.UUID          `json:"cluster_id"`
	Kind             string             `json:"kind"`
	Namespace        string             `json:"namespace"`
	OwnerKind        string             `json:"owner_kind"`
	OwnerName        string             `json:"owner_name"`
	Identity         string             `json:"identity"`
	InstalledVersion string             `json:"installed_version"`
	SourceMeta       []byte             `json:"source_meta"`
	FirstSeen        pgtype.Timestamptz `json:"first_seen"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
}

type Cluster struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	ApiServerUrl    string             `json:"api_server_url"`
	KubeconfigEnc   []byte             `json:"kubeconfig_enc"`
	KubeconfigNonce []byte             `json:"kubeconfig_nonce"`
	RbacReport      []byte             `json:"rbac_report"`
	ScheduleCron    string             `json:"schedule_cron"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastScanAt      pgtype.Timestamptz `json:"last_scan_at"`
	Status          string             `json:"status"`
	Context         string             `json:"context"`
}

type GlobalRegistryAuth struct {
	ID            uuid.UUID          `json:"id"`
	Target        string             `json:"target"`
	Kind          string             `json:"kind"`
	Method        string             `json:"method"`
	UsernameEnc   []byte             `json:"username_enc"`
	UsernameNonce []byte             `json:"username_nonce"`
	PasswordEnc   []byte             `json:"password_enc"`
	PasswordNonce []byte             `json:"password_nonce"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LatestCache struct {
	Identity      string             `json:"identity"`
	Kind          string             `json:"kind"`
	LatestVersion pgtype.Text        `json:"latest_version"`
	Candidates    []byte             `json:"candidates"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	Ttl           pgtype.Interval    `json:"ttl"`
}

type Observation struct {
	ScanID           uuid.UUID     `json:"scan_id"`
	ArtifactID       uuid.UUID     `json:"artifact_id"`
	InstalledVersion string        `json:"installed_version"`
	LatestVersion    pgtype.Text   `json:"latest_version"`
	DriftClass       string        `json:"drift_class"`
	DriftScore       float64       `json:"drift_score"`
	ReleasesBehind   pgtype.Int4   `json:"releases_behind"`
	Confidence       pgtype.Float4 `json:"confidence"`
}

type RegistryAuth struct {
	ID                uuid.UUID          `json:"id"`
	ClusterID         uuid.UUID          `json:"cluster_id"`
	Target            string             `json:"target"`
	Kind              string             `json:"kind"`
	Method            string             `json:"method"`
	SecretNamespace   pgtype.Text        `json:"secret_namespace"`
	SecretName        pgtype.Text        `json:"secret_name"`
	UsernameEnc       []byte             `json:"username_enc"`
	UsernameNonce     []byte             `json:"username_nonce"`
	PasswordEnc       []byte             `json:"password_enc"`
	PasswordNonce     []byte             `json:"password_nonce"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SecretUsernameKey pgtype.Text        `json:"secret_username_key"`
	SecretPasswordKey pgtype.Text        `json:"secret_password_key"`
}

type Scan struct {
	ID         uuid.UUID          `json:"id"`
	ClusterID  uuid.UUID          `json:"cluster_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Status     string             `json:"status"`
	Error      pgtype.Text        `json:"error"`
	Stats      []byte             `json:"stats"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	CsrfToken string             `json:"csrf_token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
