// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertObservation = `-- name: InsertObservation :exec
INSERT INTO observations (scan_id, artifact_id, installed_version, latest_version,
                          drift_class, drift_score, releases_behind, confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertObservationParams struct {
	ScanID           uuid.UUID     `json:"scan_id"`
	ArtifactID       uuid.UUID     `json:"artifact_id"`
	InstalledVersion string        `json:"installed_version"`
	LatestVersion    pgtype.Text   `json:"latest_version"`
	DriftClass       string        `json:"drift_class"`
	DriftScore       float64       `json:"drift_score"`
	ReleasesBehind   pgtype.Int4   `json:"releases_behind"`
	Confidence       pgtype.Float4 `json:"confidence"`
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.Exec(ctx, insertObservation,
		arg.ScanID,
		arg.ArtifactID,
		arg.InstalledVersion,
		arg.LatestVersion,
		arg.DriftClass,
		arg.DriftScore,
		arg.ReleasesBehind,
		arg.Confidence,
	)
	return err
}

const listObservationHistory = `-- name: ListObservationHistory :many
SELECT s.id AS scan_id, s.started_at, o.installed_version, o.latest_version,
       o.drift_class, o.drift_score, o.releases_behind
FROM observations o
JOIN scans s ON s.id = o.scan_id
WHERE o.artifact_id = $1
ORDER BY s.started_at DESC
LIMIT $2
`

type ListObservationHistoryParams struct {
	ArtifactID uuid.UUID `json:"artifact_id"`
	Limit      int32     `json:"limit"`
}

type ListObservationHistoryRow struct {
	ScanID           uuid.UUID          `json:"scan_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	InstalledVersion string             `json:"installed_version"`
	LatestVersion    pgtype.Text        `json:"latest_version"`
	DriftClass       string             `json:"drift_class"`
	DriftScore       float64            `json:"drift_score"`
	ReleasesBehind   pgtype.Int4        `json:"releases_behind"`
}

func (q *Queries) ListObservationHistory(ctx context.Context, arg ListObservationHistoryParams) ([]ListObservationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listObservationHistory, arg.ArtifactID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservationHistoryRow
	for rows.Next() {
		var i ListObservationHistoryRow
		if err := rows.Scan(
			&i.ScanID,
			&i.StartedAt,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.DriftClass,
			&i.DriftScore,
			&i.ReleasesBehind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
