// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry_auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRegistryAuth = `-- name: DeleteRegistryAuth :exec
DELETE FROM registry_auth
WHERE cluster_id = $1 AND target = $2 AND kind = $3
`

type DeleteRegistryAuthParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Target    string    `json:"target"`
	Kind      string    `json:"kind"`
}

func (q *Queries) DeleteRegistryAuth(ctx context.Context, arg DeleteRegistryAuthParams) error {
	_, err := q.db.Exec(ctx, deleteRegistryAuth, arg.ClusterID, arg.Target, arg.Kind)
	return err
}

const listRegistryAuth = `-- name: ListRegistryAuth :many
SELECT id, cluster_id, target, kind, method,
       secret_namespace, secret_name, secret_username_key, secret_password_key,
       username_enc, username_nonce, password_enc, password_nonce
FROM registry_auth
WHERE cluster_id = $1
ORDER BY target, kind
`

type ListRegistryAuthRow struct {
	ID                uuid.UUID   `json:"id"`
	ClusterID         uuid.UUID   `json:"cluster_id"`
	Target            string      `json:"target"`
	Kind              string      `json:"kind"`
	Method            string      `json:"method"`
	SecretNamespace   pgtype.Text `json:"secret_namespace"`
	SecretName        pgtype.Text `json:"secret_name"`
	SecretUsernameKey pgtype.Text `json:"secret_username_key"`
	SecretPasswordKey pgtype.Text `json:"secret_password_key"`
	UsernameEnc       []byte      `json:"username_enc"`
	UsernameNonce     []byte      `json:"username_nonce"`
	PasswordEnc       []byte      `json:"password_enc"`
	PasswordNonce     []byte      `json:"password_nonce"`
}

func (q *Queries) ListRegistryAuth(ctx context.Context, clusterID uuid.UUID) ([]ListRegistryAuthRow, error) {
	rows, err := q.db.Query(ctx, listRegistryAuth, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistryAuthRow
	for rows.Next() {
		var i ListRegistryAuthRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Target,
			&i.Kind,
			&i.Method,
			&i.SecretNamespace,
			&i.SecretName,
			&i.SecretUsernameKey,
			&i.SecretPasswordKey,
			&i.UsernameEnc,
			&i.UsernameNonce,
			&i.PasswordEnc,
			&i.PasswordNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegistryAuth = `-- name: UpsertRegistryAuth :one
INSERT INTO registry_auth (
    cluster_id, target, kind, method,
    secret_namespace, secret_name, secret_username_key, secret_password_key,
    username_enc, username_nonce, password_enc, password_nonce
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (cluster_id, target, kind)
DO UPDATE SET
    method = EXCLUDED.method,
    secret_namespace = EXCLUDED.secret_namespace,
    secret_name = EXCLUDED.secret_name,
    secret_username_key = EXCLUDED.secret_username_key,
    secret_password_key = EXCLUDED.secret_password_key,
    username_enc = EXCLUDED.username_enc,
    username_nonce = EXCLUDED.username_nonce,
    password_enc = EXCLUDED.password_enc,
    password_nonce = EXCLUDED.password_nonce
RETURNING id
`

type UpsertRegistryAuthParams struct {
	ClusterID         uuid.UUID   `json:"cluster_id"`
	Target            string      `json:"target"`
	Kind              string      `json:"kind"`
	Method            string      `json:"method"`
	SecretNamespace   pgtype.Text `json:"secret_namespace"`
	SecretName        pgtype.Text `json:"secret_name"`
	SecretUsernameKey pgtype.Text `json:"secret_username_key"`
	SecretPasswordKey pgtype.Text `json:"secret_password_key"`
	UsernameEnc       []byte      `json:"username_enc"`
	UsernameNonce     []byte      `json:"username_nonce"`
	PasswordEnc       []byte      `json:"password_enc"`
	PasswordNonce     []byte      `json:"password_nonce"`
}

func (q *Queries) UpsertRegistryAuth(ctx context.Context, arg UpsertRegistryAuthParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRegistryAuth,
		arg.ClusterID,
		arg.Target,
		arg.Kind,
		arg.Method,
		arg.SecretNamespace,
		arg.SecretName,
		arg.SecretUsernameKey,
		arg.SecretPasswordKey,
		arg.UsernameEnc,
		arg.UsernameNonce,
		arg.PasswordEnc,
		arg.PasswordNonce,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
