// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScan = `-- name: CreateScan :one
INSERT INTO scans (cluster_id, status)
VALUES ($1, 'running')
RETURNING id, cluster_id, started_at, finished_at, status, error, stats
`

func (q *Queries) CreateScan(ctx context.Context, clusterID uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan, clusterID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Error,
		&i.Stats,
	)
	return i, err
}

const finishScan = `-- name: FinishScan :exec
UPDATE scans
SET status = $2, error = $3, stats = $4, finished_at = now()
WHERE id = $1
`

type FinishScanParams struct {
	ID     uuid.UUID   `json:"id"`
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
	Stats  []byte      `json:"stats"`
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) error {
	_, err := q.db.Exec(ctx, finishScan,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.Stats,
	)
	return err
}

const getScan = `-- name: GetScan :one
SELECT id, cluster_id, started_at, finished_at, status, error, stats
FROM scans
WHERE id = $1
`

func (q *Queries) GetScan(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Error,
		&i.Stats,
	)
	return i, err
}

const listScansByCluster = `-- name: ListScansByCluster :many
SELECT id, cluster_id, started_at, finished_at, status, error, stats
FROM scans
WHERE cluster_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListScansByClusterParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListScansByCluster(ctx context.Context, arg ListScansByClusterParams) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listScansByCluster, arg.ClusterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Error,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterScanState = `-- name: UpdateClusterScanState :exec
UPDATE clusters
SET last_scan_at = now(), status = $2
WHERE id = $1
`

type UpdateClusterScanStateParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateClusterScanState(ctx context.Context, arg UpdateClusterScanStateParams) error {
	_, err := q.db.Exec(ctx, updateClusterScanState, arg.ID, arg.Status)
	return err
}
