// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, csrf_token, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	CsrfToken string             `json:"csrf_token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.token_hash, s.user_id, s.csrf_token, s.expires_at,
       u.email, u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	CsrfToken string             `json:"csrf_token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
}

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.Email,
		&i.Role,
	)
	return i, err
}
