// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, github_login, github_name, github_avatar_url, csrf_token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	TokenHash       string             `json:"token_hash"`
	GithubLogin     string             `json:"github_login"`
	GithubName      string             `json:"github_name"`
	GithubAvatarUrl string             `json:"github_avatar_url"`
	CsrfToken       string             `json:"csrf_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.GithubLogin,
		arg.GithubName,
		arg.GithubAvatarUrl,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, github_login, github_name, github_avatar_url, csrf_token, expires_at
FROM sessions
WHERE token_hash = $1 AND expires_at > now()
`

type GetSessionRow struct {
	TokenHash       string             `json:"token_hash"`
	GithubLogin     string             `json:"github_login"`
	GithubName      string             `json:"github_name"`
	GithubAvatarUrl string             `json:"github_avatar_url"`
	CsrfToken       string             `json:"csrf_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.GithubLogin,
		&i.GithubName,
		&i.GithubAvatarUrl,
		&i.CsrfToken,
		&i.ExpiresAt,
	)
	return i, err
}
