// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT oci_ttl, helmrepo_ttl, artifacthub_ttl, updated_at
FROM app_settings
WHERE id = 1
`

type GetAppSettingsRow struct {
	OciTtl         pgtype.Interval    `json:"oci_ttl"`
	HelmrepoTtl    pgtype.Interval    `json:"helmrepo_ttl"`
	ArtifacthubTtl pgtype.Interval    `json:"artifacthub_ttl"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAppSettings(ctx context.Context) (GetAppSettingsRow, error) {
	row := q.db.QueryRow(ctx, getAppSettings)
	var i GetAppSettingsRow
	err := row.Scan(
		&i.OciTtl,
		&i.HelmrepoTtl,
		&i.ArtifacthubTtl,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppSettings = `-- name: UpdateAppSettings :exec
UPDATE app_settings
SET oci_ttl = $1, helmrepo_ttl = $2, artifacthub_ttl = $3, updated_at = now()
WHERE id = 1
`

type UpdateAppSettingsParams struct {
	OciTtl         pgtype.Interval `json:"oci_ttl"`
	HelmrepoTtl    pgtype.Interval `json:"helmrepo_ttl"`
	ArtifacthubTtl pgtype.Interval `json:"artifacthub_ttl"`
}

func (q *Queries) UpdateAppSettings(ctx context.Context, arg UpdateAppSettingsParams) error {
	_, err := q.db.Exec(ctx, updateAppSettings, arg.OciTtl, arg.HelmrepoTtl, arg.ArtifacthubTtl)
	return err
}
